personal_care/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('quizapp/', include('quizapp.urls')),
]

quizapp/urls.py
from django.urls import path
from . import views

app_name = 'quizapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('create_customer/', views.create_customer, name='create_customer'),
    path('skin_quiz/', views.skin_quiz, name='skin_quiz'),
    path('skin_concerns/<str:user_name>/', views.skin_concerns, name='skin_concerns'),
    path('quiz_answers/', views.quiz_answers, name='quiz_answers'),
    path('products/<str:user_name>/', views.products, name='products'),
    path('water_info/',views.water_info),
]

quizapp/models.py
import datetime
from django.db import models
from django.utils import timezone
#from .result import oil_dry_anls
from django.core.exceptions import ObjectDoesNotExist


GENDER_CHOICES = [("1", "Male"), ("2", "Female"), ("3", "Others")]

AGE_CHOICES = (
    ("1", "18-25"),
    ("2", "26-35"),
    ("3", "36-45"),
    ("4", "46-55"),
    ("5", "55+"),
)


class Customer(models.Model):
    employee_id = models.CharField(max_length=100, unique=True)
    name = models.CharField(max_length=100)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, default='1')
    age = models.CharField(max_length=1, choices=AGE_CHOICES, default='1')
    location = models.CharField(max_length=100)

    def __str__(self):
        # return self.name
        return f'{self.employee_id} - {self.name}'
    
    @property
    def get_oil_dry(self):
        '''it's return get_oil_dry'''
        oil_dry_ctx = None #oil_dry_anls(self.employee_id)
        return oil_dry_ctx
    
    @property
    def get_hydration(self):
        '''it's return get_oil_dry'''
        try:
            hydration = Hydration.objects.get(self.employee_id)
        except ObjectDoesNotExist:
            hydration = None
        return hydration


class PersonalCare(models.Model):
    code = models.CharField(null=True, blank=True, max_length=100)
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Category(models.Model):
    personalcare = models.ForeignKey(PersonalCare, on_delete=models.CASCADE)
    code = models.CharField(null=True, blank=True, max_length=100)
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Question(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    # code = models.CharField(null=True, blank=True, max_length=100)
    code = models.IntegerField(default=0)
    name = models.CharField(max_length=200)
    # pub_date = models.DateTimeField('date published')
    pub_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    marks = models.FloatField()

    def __str__(self):
        return self.name


class QuizModal(models.Model):
    choice = models.ForeignKey(Choice, on_delete=models.CASCADE)
    pub_date = models.DateTimeField(auto_now_add=True, editable=False)
    customer = models.ForeignKey(Customer, null=True, blank=True, on_delete=models.SET_NULL)
    result = models.FloatField(default=0)

    def __str__(self):
        return str(self.choice)


class Hydration(models.Model):
    customer = models.ForeignKey(Customer, null=True, blank=True, on_delete=models.SET_NULL)
    weight = models.FloatField(default=0)
    physical_activity = models.FloatField(default=0)
    water_intake = models.FloatField(default=0)
    status = models.CharField(max_length=200)


class Concerns(models.Model):
    customer = models.ForeignKey(Customer, null=True, blank=True, on_delete=models.SET_NULL)
    category = models.ManyToManyField(Category, related_name='concerns')
    is_primary = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='is_primary')


class Products(models.Model):
    code = models.IntegerField(default=0)
    title = models.CharField(max_length=100)
    #content = models.TextField()
    cleanser = models.CharField(max_length=100)
    moisturizer = models.CharField(max_length=100)
    serum = models.CharField(max_length=100)

    def __str__(self):
        return self.title

quizapp/forms.py
import re
from django import forms
from django.core.validators import validate_email
from .models import *


class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = '__all__'

quizapp/views.py
import json
from django.db.models import Case, When, IntegerField
from django.views.decorators.csrf import csrf_exempt
from django.template.loader import render_to_string, get_template
from django.core.paginator import Paginator, EmptyPage, InvalidPage
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.core.exceptions import ObjectDoesNotExist
from .models import Choice, Question, PersonalCare, Category, QuizModal, Customer, Hydration, Concerns, Products
from .forms import CustomerForm
from .serializers import ChoiceSerializer, QuestionSerializer
from rest_framework.response import Response
from rest_framework import status
from rest_framework.decorators import api_view
from django.db.models import Q, F, Count, Sum
from .score import oil_dry_anls, sen_res_anls, acne_anls, pigmentation_anls, wrinkletight_anls, product_info

def index(request):
    """wellcome page"""
    context = {
        'form': CustomerForm()
    }
    return render(request, 'quizapp/index.html', context)


@csrf_exempt
def create_customer(request):
    """create_customer """
    data = dict()
    if request.method == "POST":
        emp_id = request.POST.get('employee_id')
        if Customer.objects.filter(employee_id=emp_id).exists():
            user_info = Customer.objects.get(employee_id=emp_id)
            data['exists'] = user_info.employee_id
            data['html_data'] = render_to_string('quizapp/customer_info.html',
            {'user_info': user_info}, request=request)
        else:
            form = CustomerForm(request.POST)
            if form.is_valid():
                fs = form.save()
                data['form_is_valid'] = True
                data['user_info'] = fs.employee_id
            else:
                data['form_is_valid'] = False
        return JsonResponse(data, safe=False)


def skin_quiz(request):
    primary = request.GET.get('primary')
    category_choice = request.GET.getlist('checkbox')
    user_name = request.GET.get('user_name')
    try:
        customer_obj = Customer.objects.get(employee_id=user_name)
    except ObjectDoesNotExist:
        customer_obj = None

    specific_concerns = [104, 105, 106]
            
    if category_choice and primary:
        category_data  = Category.objects.filter(pk__in=category_choice)
        concerns_save = Concerns()
        concerns_save.customer = customer_obj
        concerns_save.is_primary = Category.objects.get(pk=primary)
        concerns_save.save()
        for x in category_data:
            concerns_save.category.add(x)
        
        questions_data = Question.objects.filter(Q(category_id__in=category_choice) & ~Q(category__code__in=specific_concerns))
        if customer_obj.get_gender_display() == 'Male':
            questions_data = questions_data.filter(~Q(code=119)) #specific_concerns.append(119)

        if questions_data.exists():
            questions = questions_data.annotate(concern_sort=Case(When(category_id=primary, then=1), default=0, output_field=IntegerField()))
            questions.order_by('-concern_sort')
        else:
            return redirect('quizapp:products', user_name=customer_obj.employee_id)
    else:
        questions = Question.objects.filter(category__personalcare_id=1).order_by('code')
        #questions = Question.objects.filter(code__in=[107,108,109]).order_by('code')
    
    
    if primary:
        next_quiz = False
    else:
        next_quiz = True
    context = {
        'questions': questions,
        'next_quiz' : next_quiz,
        'primary' : primary
    }
    return render(request, 'quizapp/skin_quiz.html', context)


def skin_concerns(request, user_name):
    try:
        customer_id = Customer.objects.get(employee_id=user_name)
    except ObjectDoesNotExist:
        customer_id = None
    
    oil_dry_ctx = oil_dry_anls(customer_id)
    #print(oil_dry_ctx['oil_dry_analysis'])

    pc_data = get_object_or_404(PersonalCare, id=2)
    category = Category.objects.filter(personalcare_id=pc_data.id)
    context = {
        'category': category,
        'pc_data': pc_data,
        'oil_dry_ctx' : oil_dry_ctx
    }
    return render(request, 'quizapp/skin_concerns.html', context)


@csrf_exempt
def quiz_answers(request):
    data = dict()
    user_name = request.GET.get('user_name')
    user_choice = request.GET.get('user_choice')
    try:
        customer_obj = Customer.objects.get(employee_id=user_name)
    except ObjectDoesNotExist:
        customer_obj = None

    choice_data = json.loads(user_choice)

    if choice_data:
        for x in choice_data:
            try:
                choice_obj = Choice.objects.get(pk=x)
                quiz_save = QuizModal()
                quiz_save.choice = choice_obj
                quiz_save.customer = customer_obj
                quiz_save.save()
            except ObjectDoesNotExist:
                pass
                #choice_obj = get_object_or_404(Choice, pk=x) 
    data = {
        'saved': True
    }
    return JsonResponse(data, safe=False)


@csrf_exempt
def water_info(request):
    data = dict()
    if request.method == "POST":
        user_name = request.POST.get('user_name')
        weight = request.POST.get('weight')
        physical_activity = request.POST.get('physical_activity')
        water_intake = request.POST.get('water_intake')
        status = request.POST.get('status')
        
        if Customer.objects.filter(employee_id=user_name).exists():
            customer_obj = Customer.objects.get(employee_id=user_name)
            water_save = Hydration()
            water_save.customer = customer_obj
            water_save.weight = weight
            water_save.physical_activity = physical_activity
            water_save.water_intake = water_intake
            water_save.status = status
            water_save.save()
            data['is_valid'] = True
        else:
           data['is_valid'] = False
    return JsonResponse(data, safe=False)

def products(request, user_name):
    """return products information as per username"""
    try:
        customer_id = Customer.objects.get(employee_id=user_name)
    except ObjectDoesNotExist:
        customer_id = None
    oil_dry_ctx = oil_dry_anls(customer_id)
    sen_res_ctx = sen_res_anls(customer_id)
    acne_anls_ctx = acne_anls(customer_id)
    ph_anls_ctx = QuizModal.objects.get(choice__question__code=108, customer=customer_id)

    pigmentation_anls_ctx = pigmentation_anls(customer_id)
    wrinkletight_anls_ctx = wrinkletight_anls(customer_id)
    concerns_data = Concerns.objects.get(customer=customer_id)
    product_data = product_info(customer_id, oil_dry_ctx, sen_res_ctx, acne_anls_ctx)

    context = {
        'oil_dry_ctx' : oil_dry_ctx,
        'sen_res_ctx' : sen_res_ctx,
        'acne_anls_ctx' : acne_anls_ctx,
        'pigmentation_anls_ctx' : pigmentation_anls_ctx,
        'wrinkletight_anls_ctx' : wrinkletight_anls_ctx,
        'ph_anls_ctx' : ph_anls_ctx,
        'concerns' : concerns_data,
        'pro_obj' : product_data
    }
    return render(request, 'quizapp/products.html', context)

templates/quizapp/customer_info.html
<div class="modal-header">
    <h5 class="modal-title">Customer Info</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>

<div class="modal-body pt-0">
    <table class="table table-bordered mt-1">
        <tr>
            <th colspan="2" style="background-color: #0c499c;color: white">Customer Info</th>
        </tr>
        <tr>
            <th>Employee ID</th>
            <td>{{ user_info.employee_id }}</td>
        </tr>
        <tr>
            <th>Employee Name</th>
            <td>{{ user_info.name }}</td>
        </tr>
        <tr>
            <th>Gender</th>
            <td>{{ user_info.get_gender_display }}</td>
        </tr>
        <tr>
            <th>Age</th>
            <td>{{ user_info.get_age_display }}</td>
        </tr>
        <tr>
            <th>Location</th>
            <td>{{ user_info.location }}</td>
        </tr>
        <tr>
            <th colspan="2" style="text-align:right">
                <p class="mb-0">Your data is already with us, still you want to continue
                    <span><a class="" href="{% url 'quizapp:skin_quiz' %}">
                                    <br>Please proceed...&raquo;</a></span>
                </p>
            </th>
        </tr>
    </table>
</div>

templates/quizapp/index.html
{% extends 'base.html' %}{% load crispy_forms_tags %}{% load static %}

{% block content %}
<style>
    /* https://www.w3schools.com/cssref/tryit.asp?filename=trycss3_background_hero */
    html, body  { 
        background: url("/static/images/127.jpg") no-repeat center center fixed; 
        -webkit-background-size: cover;
        -moz-background-size: cover;
        -o-background-size: cover;
        background-size: cover;
    }
</style>
    <h1 class="display-1 mt-3 text-center">Personal Care</h1>
     <div>
        <h2 class="display-4 text-center">Skin Analysis</h2>
        <p></p>
        <div class="text-center"> 
           <a class="btn orb-btn show-form" data-url="{% url 'quizapp:create_customer' %}"
            data-toggle="modal" data-target="#modal-quiz">Take Quiz&nbsp;&raquo;
            </a> 
        </div> 
    </div>

    <div id="loader"></div>
    <div class="modal fade" id="modal-quiz">
        <div class="modal-dialog">
            <div class="modal-content">
                <form method="POST" data-url="{% url 'quizapp:create_customer' %}" class="create-form">
                    {% csrf_token %}
                    <div class="modal-header">
                        <h5 class="modal-title">Create Profile</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>

                    <div class="modal-body">
                        <div class="mb-6">
                            {{ form|crispy }}
                        </div>
                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary save-form">Process</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <script type="text/javascript" src="{% static 'assets/dist/js/jquery.js' %}"></script>

    <script type="application/javascript">
        $(document).ready(function () {
            //let user_name = sessionStorage.getItem("name");
            let user_name = 'user_name';
            if (user_name in sessionStorage) {
                sessionStorage.removeItem(user_name);
            }


            var SaveForm = function (e) {
                e.preventDefault();
                var form = $(this);
                $.ajax({
                    url: form.attr('data-url'),
                    data: form.serialize(),
                    type: form.attr('method'),
                    dataType: 'json',
                    success: function (data) {
                        $('#modal-quiz .modal-content').html(data.html_data);
                        if (data.exists) {
                            sessionStorage.setItem("user_name", data.exists);
                        }
                        if (data.user_info) {
                            sessionStorage.setItem("user_name", data.user_info);
                            location.href = "{% url 'quizapp:skin_quiz' %}";
                        }
                    }
                })
            };

            // create
            //$(".show-form").click(ShowForm);
            $("#modal-quiz").on("submit", ".create-form", SaveForm);

        });
    </script>
{% endblock %}

templates/quizapp/products.html
{% extends 'base.html' %}{% load crispy_forms_tags %}{% load static %}
{% block content %}
<style>
    .table td.fit, 
    .table th.fit {
        white-space: nowrap;
        width: 1%;
    }
    .container {
        margin-left:10%;
    }
    .auto-index {
        counter-reset: serial-number;
    }

    .auto-index td:first-child:before {
        counter-increment: serial-number;
        content: counter(serial-number);
    }
    .table td:first-child {
        text-align: right;
    }
   
</style>
<div class="card mt-4 shadow-sm border-info card-size">
    <div class="card-header border-info">
        <h5 class="my-0 font-weight-normal">Skin Analysis Report</h5>
    </div>
    <div class="card-body border-info">
        <table class="table table-bordered auto-index">
        <thead class="table-primary">
        <tr>
            <th class="fit">S.No</th>
            <th>Category Name</th>
            <th>Status</th>
            <th>Marks</th>
        </tr>
        </thead>
        <tbody>
        {% if oil_dry_ctx %}
        <tr>
            <td class="fit"></td>
            <td>Strip Analysis</td>
            <td>{{ oil_dry_ctx.strip_analysis }}</td>
            <td class="text-center">{{ oil_dry_ctx.strip_score }}</td>
        </tr>
        <tr>
            <td class="fit"></td>
            <td>Oil Dry Quiz Score</td>
            <td>{{ oil_dry_ctx.quiz_analysis }}</td>
            <td class="text-center">{{ oil_dry_ctx.quiz_score }}</td>
        </tr>
         <tr>
            <td class="fit"></td>
            <td colspan="3" class="font-weight-bold">
                Oil Dry Final analysis (Strip+Quiz) <span class="font-weight-normal">&nbsp;&nbsp; = {{ oil_dry_ctx.oil_dry_analysis }}</span>
            </td>
        </tr>
        <tr>
            <td class="fit"></td>
            <td colspan="3" class="">
                <span><b>Hydration Level</b>&nbsp;&nbsp;=&nbsp;&nbsp;{{ oil_dry_ctx.hydration }}</span>
                <span style="padding-left: 30%"><b>pH</b>&nbsp;&nbsp;=&nbsp;&nbsp;{{ ph_anls_ctx.choice }}</span>
            </td>
        </tr>
        {% endif %}
        <tr>
            <td class="fit"></td>
            <td>Sen-Res Score</td>
            <td>{{ sen_res_ctx.sen_res_analysis }}</td>
            <td class="text-center">{{ sen_res_ctx.sen_res_score }}</td>
        </tr>
        
        {% if concerns %}
        <tr>
            <td class="fit"></td>
            <td>Concerns</td>
            <td>Concerns: {{ concerns.category.all|join:", " }}</td>
            <td class="text-center">Primary: {{ concerns.is_primary }}</td>
        </tr>
        {% endif %}
        
        {% if acne_anls_ctx.acne_analysis %}
        <tr>
            <td class="fit"></td>
            <td>Acne Score</td>
            <td>{{ acne_anls_ctx.acne_analysis }}</td>
            <td class="text-center">{{ acne_anls_ctx.acne_score }}</td>
        </tr>
        {% endif %}
        {% if pigmentation_anls_ctx.pigmentation_analysis %}
        <tr>
            <td class="fit"></td>
            <td>Pigmentation Score</td>
            <td>{{ pigmentation_anls_ctx.pigmentation_analysis }}</td>
            <td class="text-center">{{ pigmentation_anls_ctx.pigmentation_score }}</td>
        </tr>
        {% endif %}
        {% if wrinkletight_anls_ctx.wrinkletight_analysis %}
        <tr>
            <td class="fit"></td>
            <td>Wrinkletight Score</td>
            <td>{{ wrinkletight_anls_ctx.wrinkletight_analysis }}</td>
            <td class="text-center">{{ wrinkletight_anls_ctx.wrinkletight_score }}</td>
        </tr>
        {% endif %}
        {% if pro_obj %}
        <tr>
            <td class="fit"></td>
            <td>Recommended Products</td>
            <td class="" colspan="2">({{ pro_obj.code }})&nbsp;{{ pro_obj.cleanser }}, {{ pro_obj.moisturizer }}, {{ pro_obj.serum }}</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    </div>
</div>
{% endblock %}

templates/quizapp/skin_concerns.html
{% extends 'base.html' %}{% load static %}
{% block content %}
    <style>
        .big-checkbox {
            width: 30px;
            height: 25px;
        }

        .modal-body {
            background-color: #C0C0C0;
        }

        .card-size {
            min-width: 18rem;
        }

        .modal-card-size {
            min-width: 8rem;
        }
    </style>

    <div class="card mt-4 shadow-sm border-info card-size">
        <div class="card-body border-info">
            <div class="pricing-header px-3 py-3 pt-md-3 pb-md-0 mx-auto text-center">
                <h1 class="display-4">{{ pc_data.name }}</h1>
                <p class="lead">
                    Please Select your skin concerns (Min: 1 & Max: 3)
                </p>
            </div>
            <hr class="border-info mb-0">
            <div class="card-deck mb-4 text-center">
            {% for x in category %}
                <div class="card mt-4 shadow-sm border-info card-size" id="cat-card">
                    <div class="card-header border-info">
                        <h5 class="my-0 font-weight-normal">{{ x.name }}</h5>
                    </div>
                    <div class="card-body border-info">
                        <p>information</p>
                    </div>
                    <div class="card-footer text-muted border-info">
                        <input type="checkbox" value="{{ x.id }}" class="big-checkbox primary-checkbox" name="primary" data-name="{{ x.name }}">
                        <input type="checkbox" value="{{ x.id }}" class="concerns-checkbox" name="checkbox" hidden>
                    </div>
                </div>
            {% endfor %}
        </div>
        <a class="btn btn-outline-info" href="{% url 'quizapp:index' %}">Back</a>
        <a class="btn orb-btn float-right invisible concerns" id="concernsBtn">Concerns&raquo;</a>
    </div>


    <div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" id="modal-quiz"
         aria-labelledby="myLargeModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <form method="get" action="{% url 'quizapp:skin_quiz' %}" name="concern_form">
                <input name="user_name" type="text" hidden>
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Please select skin concern you would like to address first.</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="card-deck mb-4 text-center" id="card-load"></div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Process</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    {% endblock %}
    
    {% block extraJS %}
    
    <script type="application/javascript">
        let user_name = sessionStorage.getItem("user_name");
        document.concern_form.user_name.value = user_name;
        let skin_type = "{{ oil_dry_ctx.oil_dry_analysis }}";

        let checkbox = document.querySelector('.card-deck');
        //let values = [];
        let s = new Set();
        let dry_array = ['Combination Skin (Slightly Oily)', 'Oily Skin']
        let oily_array = ['Dry Skin', 'Normal Skin']
        //https://stackoverflow.com/questions/37073774/using-lodash-push-to-an-array-only-if-value-doesnt-exist
        checkbox.onchange = (e) => {
            let elm = e.target;
            let elm_name = elm.dataset.name;
            let concernsBtn = document.getElementById('concernsBtn');

            if(e.target.checked){                
                if(elm_name === 'Dry Skin' && dry_array.includes(skin_type)){
                    alert('invalid selection');
                    elm.checked = false;
                } else if (elm_name === 'Oily Skin' && oily_array.includes(skin_type)){
                    alert('invalid selection');
                    elm.checked = false;
                } else {
                    s.add(elm.value)
                }
                
                if (s.has(String(5)) && s.has(String(10))) {
                    s.delete(elm.value);
                    elm.checked = false;
                    alert('skin concerns error: both oily and dry skin is not possible');
                } else if (s.size > 3) {
                    s.delete(elm.value);
                    elm.checked = false;
                    alert('you can select min: 1 and max: 3');
                } else if (s.size >= 1) {
                    concernsBtn.classList.remove('invisible');
                }
            } else {
                s.delete(elm.value);
            }
            //values = Array.from(s);
        }
        
        
        $(document).ready(function () {
            $(".concerns").click(function () {
                //https://jsfiddle.net/4bnx8acw/15/
                //let elm_test = document.querySelectorAll('input[type="checkbox"]:checked').copy
                let option_elm = document.querySelectorAll('input[type="checkbox"]:checked');
                let elm_clone = $(option_elm).parent().closest("#cat-card");
                $("#modal-quiz").modal('show');
                $("#card-load").html(elm_clone.clone());
                $("#card-load .card").removeClass('card-size').addClass('modal-card-size');
                $('#card-load .primary-checkbox').attr('type', 'radio');
                $('#card-load .concerns-checkbox').prop('checked', true);
            });

            $('#modal-quiz').on('hidden.bs.modal', function () {
                $("#card-load").empty();
            });

        });

    </script>
    {% endblock %}